[font]
size = 12

[font.normal]
#family = "JetBrainsMono Nerd Font"
#family = "FiraCode Nerd Font"
family = "FiraCode Nerd Font Mono"
#family = "MesloLGS Nerd Font"

[window.padding]
x = 0
y = 0

[window]
dynamic_padding = false

